# Generated by Django 4.0 on 2021-12-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=32)),
                ('part_name', models.CharField(max_length=32)),
                ('quantity', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('part_name', models.CharField(max_length=32)),
                ('vendor', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='PO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=16)),
                ('vendor', models.CharField(max_length=16)),
                ('date', models.DateTimeField(verbose_name='date ordered')),
                ('notes', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=32)),
                ('vendor_id', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Shippment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_shipped', models.DateTimeField(verbose_name='date shipped')),
                ('date_received', models.DateTimeField(verbose_name='date received')),
                ('shipped_from', models.CharField(max_length=16)),
                ('shipped_to', models.CharField(max_length=16)),
                ('shipper_receiver_id', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=128)),
                ('manager', models.CharField(max_length=64)),
                ('notes', models.CharField(max_length=256)),
                ('due_date', models.DateTimeField(verbose_name='due date')),
                ('ordered_parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.orderedpart')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.po')),
            ],
        ),
        migrations.AddField(
            model_name='orderedpart',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.po'),
        ),
    ]
