# Generated by Django 4.0 on 2021-12-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippment',
            name='ordered_parts',
        ),
        migrations.AddField(
            model_name='orderedpart',
            name='shippment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.shippment'),
        ),
    ]
