# Generated by Django 4.0 on 2021-12-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_shippment_ordered_parts_orderedpart_shippment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedpart',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
