# Generated by Django 4.0 on 2022-01-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_orderedpart_is_shipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='date',
            field=models.DateField(verbose_name='date ordered'),
        ),
        migrations.AlterField(
            model_name='shippment',
            name='date_received',
            field=models.DateField(verbose_name='date received'),
        ),
        migrations.AlterField(
            model_name='shippment',
            name='date_shipped',
            field=models.DateField(verbose_name='date shipped'),
        ),
        migrations.AlterField(
            model_name='shippment',
            name='due_date',
            field=models.DateField(verbose_name='due date'),
        ),
    ]
