# Generated by Django 4.0 on 2022-01-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_po_date_alter_shippment_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shippment',
            name='date_received',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shippment',
            name='date_shipped',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shippment',
            name='due_date',
            field=models.DateField(),
        ),
    ]
