# Generated by Django 4.0 on 2022-01-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_po_date_alter_shippment_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippment',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shippment',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='shippment',
            name='notes',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
