# Generated by Django 4.0 on 2022-01-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_orderedpart_quantity_expected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedpart',
            name='shippment',
        ),
        migrations.AddField(
            model_name='orderedpart',
            name='shippment',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Shippment'),
        ),
    ]
