# Generated by Django 4.0 on 2022-01-02 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_orderedpart_shippment_orderedpart_shippment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedpart',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='orderedpart',
            name='part_number',
        ),
        migrations.AddField(
            model_name='orderedpart',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.vendor'),
        ),
        migrations.AlterField(
            model_name='part',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.vendor'),
        ),
    ]
