# Generated by Django 4.0 on 2022-01-02 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_orderedpart_part_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedpart',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.part'),
        ),
    ]
