# Generated by Django 4.0 on 2022-01-02 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_orderedpart_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='polls.vendor'),
        ),
    ]
